package com.zy.model;

import com.jfinal.plugin.activerecord.Page;
import com.zy.model.base.BaseOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Order extends BaseOrder<Order> {
	public static final Order dao = new Order();
	
	public Page<Order> findAll(int page){
		return paginate(page, 20, "SELECT *", "FROM `order`");
	}
}
