package com.zy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrder<M extends BaseOrder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setProgress(java.lang.Integer progress) {
		set("progress", progress);
	}

	public java.lang.Integer getProgress() {
		return get("progress");
	}

	public void setMission(java.lang.String mission) {
		set("mission", mission);
	}

	public java.lang.String getMission() {
		return get("mission");
	}

	public void setInCharge(java.lang.String inCharge) {
		set("in_charge", inCharge);
	}

	public java.lang.String getInCharge() {
		return get("in_charge");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

}
